controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

jobOfferCreate:
    path: /job-offer/create
    controller: App\Controller\JobOfferController::create
    methods: GET

#
#jobOfferRead:
#    path: /job-offer/{id}
#    controller: App\Controller\JobOfferController::read
#    methods: GET
#
#jobOfferUpdate:
#    path: /job-offer/{id}/update
#    controller: App\Controller\JobOfferController::update
#    methods: PUT
#
#jobOfferDelete:
#    path: /job-offer/{id}/delete
#    controller: App\Controller\JobOfferController::delete
#    methods: DELETE
#
#jobOfferList:
#    path: /job-offer
#    controller: App\Controller\JobOfferController::index
#    methods: GET