controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

jobOfferCreate:
    path: /job-offer/create
    controller: App\Controller\JobOfferController::create
    methods: POST

jobOfferRead:
    path: /job-offer/read/{id}
    controller: App\Controller\JobOfferController::read
    methods: GET

jobOfferUpdate:
    path: /job-offer/update/{id}
    controller: App\Controller\JobOfferController::update
    methods: PUT

jobOfferDelete:
    path: /job-offer/delete/{id}
    controller: App\Controller\JobOfferController::delete
    methods: DELETE

jobOfferList:
    path: /job-offer/list
    controller: App\Controller\JobOfferController::list
    methods: GET

ContractCreate:
    path: /contract/create
    controller: App\Controller\ContractController::create
    methods: POST

ContractRead:
    path: /contract/read/{id}
    controller: App\Controller\ContractController::read
    methods: GET

ContractUpdate:
    path: /contract/update/{id}
    controller: App\Controller\ContractController::update
    methods: PUT

ContractDelete:
    path: /contract/delete/{id}
    controller: App\Controller\ContractController::delete
    methods: DELETE

ContractList:
    path: /contract/list
    controller: App\Controller\ContractController::list
    methods: GET

UserCreate:
    path: /user/create
    controller: App\Controller\UserController::create
    methods: POST

UserRead:
    path: /user/read/{id}
    controller: App\Controller\UserController::read
    methods: GET

UserUpdate:
    path: /user/update/{id}
    controller: App\Controller\UserController::update
    methods: PUT

UserDelete:
    path: /user/delete/{id}
    controller: App\Controller\UserController::delete
    methods: DELETE

UserList:
    path: /user/list
    controller: App\Controller\UserController::list
    methods: GET