controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

jobOfferCreate:
    path: /job-offer/create
    controller: App\Controller\JobOfferController::create
    methods: POST

jobOfferRead:
    path: /job-offer/read/{id}
    controller: App\Controller\JobOfferController::read
    methods: GET

jobOfferUpdate:
    path: /job-offer/update/{id}
    controller: App\Controller\JobOfferController::update
    methods: PUT

jobOfferDelete:
    path: /job-offer/delete/{id}
    controller: App\Controller\JobOfferController::delete
    methods: DELETE

jobOfferList:
    path: /job-offer/list
    controller: App\Controller\JobOfferController::list
    methods: GET

ContractCreate:
    path: /contract/create
    controller: App\Controller\ContractController::create
    methods: POST

ContractRead:
    path: /contract/read/{id}
    controller: App\Controller\ContractController::read
    methods: GET

ContractUpdate:
    path: /contract/update/{id}
    controller: App\Controller\ContractController::update
    methods: PUT

ContractDelete:
    path: /contract/delete/{id}
    controller: App\Controller\ContractController::delete
    methods: DELETE

ContractList:
    path: /contract/list
    controller: App\Controller\ContractController::list
    methods: GET

UserCreate:
    path: /user/create
    controller: App\Controller\UserController::create
    methods: POST

UserRead:
    path: /user/read/{id}
    controller: App\Controller\UserController::read
    methods: GET

UserUpdate:
    path: /user/update/{id}
    controller: App\Controller\UserController::update
    methods: PUT

UserDelete:
    path: /user/delete/{id}
    controller: App\Controller\UserController::delete
    methods: DELETE

UserList:
    path: /user/list
    controller: App\Controller\UserController::list
    methods: GET

GetUserFromToken:
    path: /user/get-from-token
    controller: App\Controller\UserController::getUserFromToken
    methods: GET

CandidateCreate:
    path: /candidate/create
    controller: App\Controller\CandidateController::create
    methods: POST

CandidateRead:
    path: /candidate/read/{id}
    controller: App\Controller\CandidateController::read
    methods: GET

CandidateUpdate:
    path: /candidate/update/{id}
    controller: App\Controller\CandidateController::update
    methods: PUT

CandidateDelete:
    path: /candidate/delete/{id}
    controller: App\Controller\CandidateController::delete
    methods: DELETE

CandidateList:
    path: /candidate/list
    controller: App\Controller\CandidateController::list
    methods: GET

CandidateUploadAvatar:
    path: /candidate/upload-avatar
    controller: App\Controller\CandidateController::uploadAvatar
    methods: POST

CompanyCreate:
    path: /company/create
    controller: App\Controller\CompanyController::create
    methods: POST

CompanyRead:
    path: /company/read/{id}
    controller: App\Controller\CompanyController::read
    methods: GET

CompanyUpdate:
    path: /company/update/{id}
    controller: App\Controller\CompanyController::update
    methods: PUT

CompanyDelete:
    path: /company/delete/{id}
    controller: App\Controller\CompanyController::delete
    methods: DELETE

CompanyList:
    path: /company/list
    controller: App\Controller\CompanyController::list
    methods: GET

CompanyTopOffers:
    path: /company/top-offers
    controller: App\Controller\CompanyController::topOffers
    methods: GET

Login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: POST

ImageCreate:
    path: /image/create
    controller: App\Controller\ImageController::create
    methods: POST

ImageRead:
    path: /image/read/{fileName}
    controller: App\Controller\ImageController::read
    methods: GET

ImageUpdate:
    path: /image/update
    controller: App\Controller\ImageController::update
    methods: PUT

ImageDelete:
    path: /image/delete/{fileName}
    controller: App\Controller\ImageController::delete
    methods: DELETE

ImageList:
    path: /image/list
    controller: App\Controller\ImageController::list
    methods: GET